const $=s=>document.querySelector(s),toast=m=>{ $('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)};let state,activeProject,activeAudit,supabase;
const apiWithAuth=async(p,o={})=>{if(supabase){const {data}=await supabase.auth.getSession();if(data.session)o.headers={...(o.headers||{}),Authorization:`Bearer `};}return api(p,o)};
const api=async(p,o={})=>{const r=await fetch(p,{headers:{'content-type':'application/json'},...o}),d=await r.json();if(!r.ok)throw Error(d.error);return d};const open=id=>{const e=$('#'+id);e.hidden=false;requestAnimationFrame(()=>e.classList.add('open'))},close=id=>{const e=$('#'+id);e.classList.remove('open');setTimeout(()=>e.hidden=true,180)};
async function load(){try{state=await apiWithAuth('/api/dashboard');$('#authScreen').style.display='none';$('#app').hidden=false;$('#welcome').textContent=`Keep shipping, ${state.user.name.split(' ')[0]}.`;$(`#today`).textContent=new Date().toDateString().toUpperCase();$('#sideName').textContent=state.user.name;$('#sideRole').textContent=state.user.role;$('#adminPanel').hidden=state.user.role!=='admin';if(state.user.role==='admin'){document.body.classList.add('is-admin');$('#adminPanel').scrollIntoView({block:'nearest'});renderAdmin()}render();}catch(e){if(e.message!=='Authentication required')toast(e.message)}}
function renderAdmin(){const counts=state.projects.reduce((a,p)=>(a[p.category]=(a[p.category]||0)+1,a),{});$('#adminProjects').innerHTML=`<div class="admin-summary"><span><strong>${state.projects.length}</strong> live projects</span><span><strong>${counts.IMPERATIVE||0}</strong> Imperative</span><span><strong>${counts['FULL-STACK']||0}</strong> Full-stack</span><span><strong>${counts.ARCHITECTURE||0}</strong> Architecture</span></div><p class="admin-note">Changes here are live. Students see active projects in this order as soon as they refresh their dashboard.</p>${state.projects.map(p=>`<div class="admin-project"><span>${p.category} · ${p.order}</span><strong>${p.title}</strong><button data-remove="${p.id}">Remove</button></div>`).join('')}`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this project from the student track?'))return;await api('/api/admin/projects/'+b.dataset.remove,{method:'DELETE'});toast('Project removed from the live track');load()})}
function render(){let passed=state.projects.filter(p=>p.submission?.status==='passed').length;$('#progressNumber').textContent=`${passed} / ${state.projects.length}`;$('#progressBar').style.width=state.projects.length?passed/state.projects.length*100+'%':'0%';let cur=state.projects.find(p=>p.unlocked&&!p.submission);$('#currentCategory').textContent=cur?.category||'Complete';$('#currentTitle').textContent=cur?.title||'All available projects passed';$('#projectList').innerHTML=state.projects.map(p=>`<div class="project-row"><div><span class="kicker">${p.category} · PROJECT ${p.order}</span><strong>${p.title}</strong><small>${p.submission?.status||(!p.unlocked?'Locked':'Ready to start')}</small></div><button class="button button-coral" data-p="${p.id}" ${!p.unlocked||p.submission?'disabled':''}>${p.unlocked&&!p.submission?'Open':p.submission?.status||'Locked'}</button></div>`).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{activeProject=state.projects.find(p=>p.id===b.dataset.p);$('#modalCategory').textContent=activeProject.category;$('#modalTitle').textContent=activeProject.title;$('#projectBrief').textContent=activeProject.markdown;open('projectModal')});let a=state.assignments;$('#auditCount').textContent=a.length;$('#queueCount').textContent=`${a.length} waiting`;$('#waitingNumber').textContent=a.length;$('#auditList').innerHTML=a.length?a.map(x=>`<div class="audit-item"><div><strong>${x.project.title}</strong><span>by ${x.student.name}</span></div><button class="round-arrow" data-a="${x.id}">→</button></div>`).join(''):'<p class="muted">No assignments yet.</p>';document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{activeAudit=a.find(x=>x.id===b.dataset.a);$('#auditTitle').textContent=`Review ${activeAudit.project.title}`;$('#auditRepo').textContent=activeAudit.submission.repository;open('auditModal')})}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});load()}catch(x){$('#loginError').textContent=x.message}};$('#logoutButton').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#submissionForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/projects/'+activeProject.id+'/submit',{method:'POST',body:JSON.stringify({repository:$('#repository').value})});close('projectModal');toast('Submitted for peer audit');load()}catch(x){$('#submissionError').textContent=x.message}};$('#auditForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/audits/'+activeAudit.id,{method:'POST',body:JSON.stringify({code:$('#auditInput').value,score:$('#auditScore').value,feedback:$('#auditFeedback').value})});close('auditModal');toast('Audit submitted');load()}catch(x){$('#auditError').textContent=x.message}};load();
$('#projectForm').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);try{await api('/api/admin/projects',{method:'POST',body:JSON.stringify({title:d.get('title'),category:d.get('category'),order:d.get('order'),markdown:await d.get('brief').text()})});e.target.reset();toast('Project uploaded');load()}catch(x){toast(x.message)}};
document.querySelectorAll('.nav-item').forEach(link=>link.addEventListener('click',e=>{const target=link.getAttribute('href');if(target==='#audits')document.getElementById('audits')?.scrollIntoView({behavior:'smooth'});else if(target==='#track')document.getElementById('track')?.scrollIntoView({behavior:'smooth'});else if(target==='#overview')window.scrollTo({top:0,behavior:'smooth'});}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.modal-backdrop.open').forEach(m=>close(m.id));}});

function renderJourney(){if(!state?.projects)return;const rail=$('#journeyRail');if(!rail)return;const passed=state.projects.filter(p=>p.submission?.status==='passed').length;const current=state.projects.find(p=>p.unlocked&&!p.submission);$('#journeySummary').textContent=`${passed} of ${state.projects.length} milestones`;rail.innerHTML=state.projects.map((p,i)=>{const status=p.submission?.status==='passed'?'complete':p===current?'current':p.unlocked?'upcoming':'locked';const icon=status==='complete'?'✓':status==='current'?'●':status==='locked'?'○':'→';return `<div class="journey-step ${status}"><span class="journey-node">${icon}</span><div><small>0${i+1}</small><strong>${p.title}</strong><em>${status==='complete'?'Complete':status==='current'?'Continue next':'Locked until unlocked'}</em></div></div>`}).join('')}

// Supabase is optional in local demo mode; when configured it owns the session.
(async()=>{try{const config=await fetch('/api/config').then(r=>r.json());if(window.supabase&&config.supabaseUrl&&config.supabaseAnonKey){supabase=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey);$('#loginForm').onsubmit=async e=>{e.preventDefault();const c=Object.fromEntries(new FormData(e.target));const {error}=await supabase.auth.signInWithPassword(c);if(error)$('#loginError').textContent=error.message;else load()};supabase.auth.onAuthStateChange((_event,session)=>{if(session)load()});}}catch{}})();
setInterval(renderJourney,500);
